site_name: dontreadme-api
title: dontreadme-api
url: https://dontreadme-api.com

nav:
  - Home: index.md
  - API Reference: api.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        numpy: {type: numpy}

theme:
    name: readthedocs
